server.port=9090
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false
spring.sql.init.mode=always
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=stat
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:stat
spring.application.name=stats-server
spring.cloud.config.enabled=false


logging.level.ru.practicum.stat.server=DEBUG

eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
eureka.client.instance.preferIpAddress=true
eureka.client.instance.hostname=localhost
eureka.client.instance.instance-id=${spring.application.name}:${random.value}
eureka.client.instance.leaseRenewalIntervalInSeconds=10