server.port=9090
spring.datasource.url=${SPRING_DATASOURCE_URL_STAT_SERVER}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_STAT_SERVER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_STAT_SERVER}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false