CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(16) NOT NULL,
    created TIMESTAMP NOT NULL
);