spring.datasource.url=jdbc:postgresql://stats-server-db:5432/ewm-stat
spring.datasource.username=stat
spring.datasource.password=stat
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false
spring.sql.init.mode=always