server:
  port: 0

grpc:
  server:
    port: 0
    reflection-service-enabled: true

spring:
  application:
    name: collector
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      retry:
        useRandomPolicy: true
        max-interval: 6000
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      grpcPort: ${grpc.server.port}

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    ru.practicum: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{36} : %msg%n"

kafka:
  producer:
    group-id: collector-producer
    client-id: collector-${random.uuid}
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: serializer.AvroSerializer