server:
  port: 0

spring:
  application:
    name: category-service
  datasource:
    url: jdbc:postgresql://category-db:5432/ewm-category
    username: category
    password: category
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}