spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          default-label: main
          search-paths: '{application}'

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka