spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:./config-repo

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka