services:
  stat-server:
    build: stat/stats-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stat-server-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_STAT_SERVER}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_STAT_SERVER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_STAT_SERVER}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      timeout: 5s
      interval: 5s
      retries: 10

  stat-server-db:
    image: postgres:16.1
    container_name: stat-server-db
    volumes:
      - ./stat/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_STAT_SERVER}
      - POSTGRES_USER=${POSTGRES_USER_STAT_SERVER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_STAT_SERVER}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      stat-server:
        condition: service_healthy
      ewm-main-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_MAIN_SERVICE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_MAIN_SERVICE}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_MAIN_SERVICE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-main-db:
    image: postgres:16.1
    container_name: ewm-main-db
    volumes:
      - ./main-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_MAIN_SERVICE}
      - POSTGRES_USER=${POSTGRES_USER_MAIN_SERVICE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MAIN_SERVICE}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10