server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5432/ewm-user   # или общая БД
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}