server:
  port: 0

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:postgresql://rating-db:5432/ewm-rating
    username: rating
    password: rating
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}