server:
  port: 0

spring:
  application:
    name: request-service
  datasource:
    url: jdbc:postgresql://request-db:5432/ewm-request
    username: request
    password: request
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}